# Generated by Django 4.0.3 on 2023-12-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='handlers',
            name='assignment_count',
            field=models.IntegerField(default=0),
        ),
    ]
