# Generated by Django 4.0.3 on 2023-12-25 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0002_handlers_assignment_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidents',
            name='assigned_to',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='incident.handlers'),
        ),
    ]
